import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "@/myComponents/Navbar/Navbar";
import Footer from "@/myComponents/Footer/Footer";
import { Toaster } from "sonner";
import SessionServerProvider from "@/myComponents/SessionServerProvider/SessionServerProvider";
import 'react-loading-skeleton/dist/skeleton.css';
import CreateContextProvider from '@/Context/CartAndWishlist'

const exo = Exo({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={exo.className}
      >
        <SessionServerProvider>
          <CreateContextProvider>
            <Toaster />
            <Navbar />
            {children}
            <Footer />
          </CreateContextProvider>
        </SessionServerProvider>
      </body>
    </html>
  );
}
